server:
  port: 8888

spring:
  application:
    name: config-service

eureka:
  instance:
    hostname: localhost
    health-check-url-path: /health
    status-page-url-path: /info
    home-page-url-path: /
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
